### ISSUE TITLE
Adaptar rodapé para novo layout

### ISSUE THREAD

**Issue by hugoramos** [trilogotec/trivagas-web#11]
https://xd.adobe.com/view/158e3a84-2c4b-4219-77ef-28746f08aa01-63bf/

**Comment by hileomsi** [comment]
O rodapé não teve mudança.
![Screen Shot 2020-02-08 at 11 06 01](https://user-images.githubusercontent.com/12954134/74086619-40f16100-4a63-11ea-86f2-1c945b713cb6.png)
